"""Create tables

Revision ID: 3a9941a2fb3d
Revises: 8405f0fa8863
Create Date: 2022-11-24 19:13:45.851592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a9941a2fb3d'
down_revision = '8405f0fa8863'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application', 'person_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('application', 'job_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('job', 'creator_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job', 'creator_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('application', 'job_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('application', 'person_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
