"""Create user model

Revision ID: ddcbeeaad9f8
Revises: c3af0b46fadc
Create Date: 2022-11-10 02:41:33.492003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddcbeeaad9f8'
down_revision = 'c3af0b46fadc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('username', sa.String(length=45), nullable=False))
    op.add_column('person', sa.Column('password', sa.String(length=45), nullable=False))
    op.add_column('person', sa.Column('email', sa.String(length=45), nullable=False))
    op.create_unique_constraint(None, 'person', ['password'])
    op.create_unique_constraint(None, 'person', ['username'])
    op.create_unique_constraint(None, 'person', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'person', type_='unique')
    op.drop_constraint(None, 'person', type_='unique')
    op.drop_constraint(None, 'person', type_='unique')
    op.drop_column('person', 'email')
    op.drop_column('person', 'password')
    op.drop_column('person', 'username')
    # ### end Alembic commands ###
